import Head from "next/head";
import type { AppProps } from "next/app";
import "../styles/globals.css";
import "../styles/custom.css";

import Favicon from "../components/atoms/Favicon";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Vilebloom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* font */}
        <link
          rel="preload"
          href="/meltow-font/MeltowSan100-Rust.woff2"
          as="font"
          type="font/woff2"
          crossOrigin=""
        ></link>
        <link
          rel="preload"
          href="/meltow-font/MeltowSan200-Rust.woff2"
          as="font"
          type="font/woff2"
          crossOrigin=""
        ></link>
        <link
          rel="preload"
          href="/meltow-font/MeltowSan300-Rust.woff2"
          as="font"
          type="font/woff2"
          crossOrigin=""
        ></link>
        <Favicon type="light" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
